version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: flask_server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: flask_client
    stdin_open: true
    tty: true
    depends_on:
      - server
    restart: on-failure

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi:ro
    depends_on:
      - server
