// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "http://localhost:5000"
  },
  environment: {
    "Current Value": "",
    testUsername: "",
    testEmail: "",
    loginBody: "",
    testProductName: "",
    skipProductRequest: "",
    jwtToken: "",
    productId: ""
  }
});

export default function() {
  group("register", function() {
    postman[Request]({
      name: "Đăng ký tài khoản người dùng mới",
      id: "f3d60dc0-7e51-447c-89b5-662c0478c3fd",
      method: "POST",
      address: "{{baseUrl}}/register",
      data:
        '{\n  "username": "{{testUsername}}",\n  "password": "123456",\n  "email": "{{testEmail}}",\n  "fullName": "Test User"\n}\n',
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json"
      },
      pre() {
        // dùng timestamp để chắc chắn unique
        const timestamp = Date.now();
        pm.environment.set("testUsername", `user_${timestamp}`);
        pm.environment.set("testEmail", `user_${timestamp}@example.com`);
        pm.environment.unset("jwtToken");
        pm.environment.unset("productId");
      },
      post(response) {
        pm.test("Status code is 201", () => pm.response.to.have.status(201));

        const json = pm.response.json();

        // Lưu token để dùng cho request sau
        pm.environment.set("jwtToken", json.token);

        // Test message và token
        pm.test("User created successfully", () => {
          pm.expect(json.message).to.eql("Đăng ký thành công");
          pm.expect(json.token).to.be.a("string").and.not.empty;
        });
      }
    });
  });

  group("login", function() {
    postman[Request]({
      name: "Đăng nhập vào hệ thống",
      id: "b94ea47f-a353-4072-b234-f424193c81de",
      method: "POST",
      address: "{{baseUrl}}/login",
      data: "{{loginBody}}\n",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json"
      },
      pre() {
        // Dùng lại username đã đăng ký ở bước register
        const username = pm.environment.get("testUsername");
        pm.environment.set(
          "loginBody",
          JSON.stringify({
            username: username,
            password: "123456"
          })
        );
      },
      post(response) {
        pm.test("Status code is 200", () => pm.response.to.have.status(200));
        const json = pm.response.json();
        pm.environment.set("jwtToken", json.token);

        pm.test("JWT token is saved", () => {
          pm.expect(pm.environment.get("jwtToken")).to.be.a("string");
        });
      }
    });
  });

  group("products", function() {
    group("{id}", function() {
      postman[Request]({
        name: "Lấy danh sách tất cả sản phẩm",
        id: "54f569d0-2331-4960-a9b6-be8bb70292da",
        method: "GET",
        address: "{{baseUrl}}/products",
        headers: {
          Accept: "application/json"
        },
        post(response) {
          pm.test("Status code is 200", () => pm.response.to.have.status(200));
          pm.test("Response is an array", () => {
            pm.expect(Array.isArray(pm.response.json())).to.be.true;
          });
        },
        auth(config, Var) {
          config.headers.Authorization =
            "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDlmY2NkY2ZiMTFlM2VmYjI1ZDJkZCIsInVzZXJuYW1lIjoibmd1eWVubWFuaHF1eW5oIiwiaWF0IjoxNzYyODIyODI0LCJleHAiOjE3NjI4MjY0MjR9.Oq2lNg4JMTFvCxbxYOxXNd6IUQgYg51_qt8SARypLtc";
        }
      });

      postman[Request]({
        name: "(Admin) Tạo mới sản phẩm",
        id: "7c414499-ff55-4b3b-9476-e30619cda855",
        method: "POST",
        address: "{{baseUrl}}/products",
        data:
          '{\n  "name": "{{testProductName}}",\n  "category": "Tâm lý kỹ năng",\n  "type": "book",\n  "price": 135000,\n  "stock": 10,\n  "description": "Sách test tự động",\n  "images": ["https://example.com/images/test.jpg"]\n}\n',
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json"
        },
        pre() {
          // Gắn token vào header Authorization
          pm.request.headers.add({
            key: "Authorization",
            value: `Bearer ${pm.environment.get("jwtToken")}`
          });
          // dùng timestamp để chắc chắn unique
          const timestamp = Date.now();
          pm.environment.set("testProductName", `Sách Test ${timestamp}`);
        },
        post(response) {
          // Kiểm tra status code 201
          pm.test("Status code is 201", () => pm.response.to.have.status(201));

          // Lấy response JSON
          const json = pm.response.json();
          pm.environment.set("productId", json._id);

          // Lưu productId vào environment
          if (json._id) {
            pm.environment.set("productId", json._id);
            console.log("Saved productId:", json._id);
          } else {
            pm.environment.set("productId", null);
            console.warn("No productId returned!");
          }

          // Kiểm tra tên product
          pm.test("Product created successfully", () => {
            pm.expect(json.name).to.eql(pm.environment.get("testProductName"));
          });
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("bearerToken")}`;
        }
      });

      postman[Request]({
        name: "Lấy chi tiết một sản phẩm",
        id: "3035c8e6-39f1-45cb-afc0-bd7284c8cae4",
        method: "GET",
        address: "{{baseUrl}}/products/{{productId}}",
        headers: {
          Accept: "application/json"
        },
        pre() {
          let productId = pm.environment.get("productId");

          // Kiểm tra
          if (!productId || productId === "null") {
            console.warn("No productId, skipping request");
            pm.environment.set("skipProductRequest", true);
          } else {
            pm.environment.set("skipProductRequest", false);
            pm.variables.set("productId", productId); // Cập nhật URL
          }
        },
        post(response) {
          // Kiểm tra flag từ pre-request
          let skipRequest = pm.environment.get("skipProductRequest");

          if (skipRequest === "true") {
            console.log("Request skipped, no response to parse");
          } else {
            try {
              let jsonData = pm.response.json();
              console.log("Response JSON:", jsonData);

              // Thêm assertion
              pm.test("Status code is 200", function() {
                pm.response.to.have.status(200);
              });
            } catch (e) {
              console.error("JSON parse error:", e);
              pm.test("Response is valid JSON", function() {
                pm.expect(false).to.be.true;
              });
            }
          }
        }
      });

      postman[Request]({
        name: "(Admin) Cập nhật thông tin sản phẩm",
        id: "92cdade9-ba13-4ab7-884d-e4e11445e7e9",
        method: "PUT",
        address: "{{baseUrl}}/products/{{productId}}",
        data: '{\n  "price": 150000,\n  "stock": 5\n}\n',
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json"
        },
        pre() {
          pm.request.headers.add({
            key: "Authorization",
            value: `Bearer ${pm.environment.get("jwtToken")}`
          });
          const productId = pm.environment.get("productId");
          if (!productId) {
            console.log("No productId, skipping request to avoid CastError");
            postman.setNextRequest(null); // bỏ qua request
          }
        },
        post(response) {
          pm.test("Status code is 200", () => pm.response.to.have.status(200));

          const json = pm.response.json();
          pm.test("Price updated", () => {
            pm.expect(json.price).to.eql(150000);
          });
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("bearerToken")}`;
        }
      });

      postman[Request]({
        name: "(Admin) Xóa sản phẩm",
        id: "56129509-c6f8-44a1-9a39-1d06d2f3a1d3",
        method: "DELETE",
        address: "{{baseUrl}}/products/{{productId}}",
        pre() {
          pm.request.headers.add({
            key: "Authorization",
            value: `Bearer ${pm.environment.get("jwtToken")}`
          });
          const productId = pm.environment.get("productId");
          if (!productId) {
            console.log("No productId, skipping request to avoid CastError");
            postman.setNextRequest(null); // bỏ qua request
          }
        },
        post(response) {
          pm.test("Status code is 204", () => pm.response.to.have.status(204));
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("bearerToken")}`;
        }
      });
    });
  });

  group("categories", function() {
    postman[Request]({
      name: "Lấy danh sách danh mục sản phẩm",
      id: "53d38c67-1f1b-46f7-8729-05629105dd7f",
      method: "GET",
      address: "{{baseUrl}}/categories",
      headers: {
        Accept: "application/json"
      }
    });
  });
}
